# Generated by Django 2.1.3 on 2020-11-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Starring', models.CharField(max_length=100)),
                ('imgs', models.CharField(max_length=100)),
                ('a', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
